### ISSUE TITLE
Pip fail

### ISSUE THREAD

**Issue by gustaveen** [Frojd/Frojd-Fabric-CLI#9]
Collecting frojd-fabric-cli
  Using cached frojd_fabric_cli-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/mj/_p8l5hnj7rg3_b7q1j7t0sg80000gn/T/pip-build-dJzYXa/frojd-fabric-cli/setup.py", line 23, in <module>
        install_requires = [str(ir.req) for ir in requires]
      File "/Users/gustav/Sites/HRF-Kongresswebben/venv/lib/python2.7/site-packages/pip/req/req_file.py", line 72, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mj/_p8l5hnj7rg3_b7q1j7t0sg80000gn/T/pip-build-dJzYXa/frojd-fabric-cli

**Comment by marteinn** [comment]
Commit 84b3013ea922c963cb4a7aba02f5454744421a91 solves this issue.
